[package]
name = "my_pest"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Basic parser that uses pest crate and code example from its documentation"

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
